baseURL = 'https://mackeracher.com/'
languageCode = 'en-us'
title = 'Anson MacKeracher'
theme = "typo"

[params]
description = "Personal webpage of Anson MacKeracher"
paginationSize = 20
faviconPath = "https://mackeracher.com"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Breadcrumbs
[params.breadcrumbs]
enabled = false

# Google analytics code
[services]
  [services.googleAnalytics]
    ID = 'G-PZQVLV2HE8'

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/amackera"

[[params.social]]
name = "github"
url = "https://github.com/amackera"

[[params.social]]
name = "HN"
url = "https://news.ycombinator.com/user?id=amackera"

[[params.social]]
name = "Email"
url = "mailto:anson@mackeracher.com"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "cv"
url = "/cv"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "photos"
url = "/photos"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'
